spring:
  application:
    name: example-liquibase
  datasource:
    type: com.mysql.cj.jdbc.MysqlDataSource
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://${MYSQL_HOST:mysql}:${MYSQL_PORT:3306}/${MYSQL_SCHEMA:test}
    username: ${MYSQL_USERNAME:root}
    password: ${MYSQL_PASSWORD:root}